dataset_name: celeba
data_root: ./data/celeba_hq_256

img_size: 128
img_channels: 3

latent_dim: 256
num_codebook_vectors: 1024

beta: 0.25
lr: 0.0000225

disc_start: 10000
disc_factor: 1.0
rec_loss_factor: 1.0
perceptual_loss_factor: 1.0

device: cuda:1
epochs: 100
batch_size: 6

# adam optimizer
beta1: 0.5
beta2: 0.9
