
dataset_name: celeba
data_root: /home/jeeves/JJ_Projects/data/celeba_hq_256

img_size: 64
img_channels: 3

latent_dim: 64
num_codebook_vectors: 256

beta: 0.25
lr: 0.0002

beta1: 0.0
beta2: 0.999

disc_start: 10000
disc_factor: 1.0
rec_loss_factor: 1.0
perceptual_loss_factor: 1.0

device: cuda:0
epochs: 15
batch_size: 16

