dataset_name: mnist
data_root: ./data

dim: 32
n_embedding: 32
img_size: 28
img_channels: 1

vqvae_epochs: 10
gen_model_epochs: 10
vqvae_batch_size: 256
gen_model_batch_size: 256
n_sample: 16

alpha: 1  # weight for embedding loss
beta: 0.25  # weight for commmitment loss
lr: 0.0002

pixelcnn_dim: 128
pixelcnn_linear_dim: 32
pixelcnn_n_blocks: 15

device: cuda:1
save_dir: mnist_work_dirs